# Site settings
title: "Ignacio Villanueva - Front-end Developer, focusing on CSS and Sass, architecture, front-end performance and responsive web design."
email: IgnaciodeNuevo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm Ignacio Villanueva, Front-end Developer, focusing on CSS and Sass, architecture, front-end performance and responsive web design.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ignaciodenuevo.com" # the base hostname & protocol for your site
twitter_username: IgnaciodeNuevo
github_username:  IgnaciodeNuevo

# Build settings
markdown: kramdown
paginate_path: /blog/page:num
paginate: 10
permalink: pretty
sass:
  style: :compressed
gems:
  - jekyll-feed
  - jekyll-sitemap